=== rodrigodelama/PFAT_practicas_22_23/XML/ord15-16/ord15-16.dtd
<!ELEMENT matrixE (filaE+)>
<!ATTLIST matrixE
          totalCe1das CDATA #IMPLIED>

<!ELEMENT filaE (celdaE+)>
<!ATTLIST filaE
          celdas CDATA #IMPLIED>

<!ELEMENT celdaE (#PCDATA)>

=== rodrigodelama/PFAT_practicas_22_23/XML/ord15-16/try.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matrixE SYSTEM "ord15-16.dtd">

<matrixE>
<filaE><celdaE>1</celdaE><celdaE>0</celdaE><celdaE>2</celdaE></filaE>
<filaE><celdaE>3</celdaE><celdaE>1</celdaE><celdaE>5</celdaE></filaE>
<filaE><celdaE>0</celdaE><celdaE>1</celdaE><celdaE>2</celdaE></filaE>
</matrixE>
