=== rodrigodelama/PFAT_practicas_22_23/XML/peli.dtd
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (titulo, director, anio, duracion, protagonistas, generos, nacionalidades)>
<!ATTLIST pelicula indice CDATA #IMPLIED>

<!ELEMENT titulo (#PCDATA)>

<!ELEMENT director (#PCDATA)>

<!ELEMENT anio (#PCDATA)>

<!ELEMENT duracion (#PCDATA)>

<!ELEMENT protagonistas (actor+)>

<!ELEMENT actor (#PCDATA)>
<!ATTLIST actor nombre CDATA #REQUIRED>

<!ELEMENT generos (genero+)>
<!ELEMENT genero (#PCDATA)>

<!ELEMENT nacionalidades (nacionalidad+)>
<!ELEMENT nacionalidad (#PCDATA)>


<!--
    NOTES:
    <!ATTLIST nombre_elemento atributo tipo_valor_atributo valor_por_defecto>
    <!ATTLIST nombreElemento nombreAtributo1 tipoAtributo1 valorInicialAtributo1>
    <!ATTLIST nombreElemento nombreAtributo2 tipoAtributo2 valorInicialAtributo2>

    CLASS CODE:
    <!ELEMENT TestSpec ((Test | GrupoTest)+)>
    <!ATTLIST TestSpec ext CDATA #REQUIRED>

    <!ELEMENT GrupoTest (EMPTY)>
    <!ATTLIST GrupoTest tipo (lex|sint|sem) #REQUIRED num CDATA #REQUIRED>

    <!ELEMENT Test (Comentario?, Ejecucion*)>
    <!ATTLIST Test tipo CDATA #IMPLIED privado (si|no) #IMPLIED id CDATA #REQUIRED genClass CDATA #IMPLIED>

    <!ELEMENT Ejecucion (Argumento*, Resultado*)>

    <!ELEMENT Argumento (#PCDATA)>

    <!ELEMENT Resultado (#PCDATA)>

    <!ELEMENT Comentario (ANY)>

    <!ATTLIST Comentario pt CDATA #IMPLIED>

-->

=== rodrigodelama/PFAT_practicas_22_23/XML/pelis3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE peliculas SYSTEM "peli.dtd">
<peliculas>
    <pelicula indice="1">
        <titulo>The Shawshank Redemption</titulo>
        <director>Frank Darabont</director>
        <anio>1994</anio>
        <duracion>142</duracion>
        <protagonistas>
        <actor nombre="Tim Robbins" />
        <actor nombre="Morgan Freeman" />
        </protagonistas>
        <generos>
        <genero>Drama</genero>
        <genero>Crime</genero>
        </generos>
        <nacionalidades>
        <nacionalidad>USA</nacionalidad>
        </nacionalidades>
    </pelicula>
    <pelicula indice="2">
        <titulo>Pulp Fiction</titulo>
        <director>Quentin Tarantino</director>
        <anio>1994</anio>
        <duracion>154</duracion>
        <protagonistas>
        <actor nombre="John Travolta" />
        <actor nombre="Samuel L. Jackson" />
        <actor nombre="Uma Thurman" />
        </protagonistas>
        <generos>
        <genero>Crime</genero>
        <genero>Drama</genero>
        <genero>Thriller</genero>
        </generos>
        <nacionalidades>
        <nacionalidad>USA</nacionalidad>
        </nacionalidades>
    </pelicula>
</peliculas>

=== rodrigodelama/PFAT_practicas_22_23/XML/pelis.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE peliculas SYSTEM "peli.dtd">
<peliculas>
    <pelicula indice="1">
        <titulo>La La Land</titulo>
        <director>Damien Chazelle</director>
        <anio>2016</anio>
        <duracion>128</duracion>
        <protagonistas>
            <actor nombre="Ryan Gosling">Sebastian Wilder</actor>
            <actor nombre="abc">Mia Dolan</actor>
        </protagonistas>
        <generos>
            <genero>Musical</genero>
            <genero>Comedia</genero>
            <genero>Romance</genero>
        </generos>
        <nacionalidades>
            <nacionalidad>Estados Unidos</nacionalidad>
        </nacionalidades>
    </pelicula>

    <pelicula>
        <titulo>The Shawshank Redemption</titulo>
        <director>Frank Darabont</director>
        <anio>1994</anio>
        <duracion>142</duracion>
        <protagonistas>
            <actor nombre="Tim Robbins"/>
            <actor nombre="Morgan Freeman"/>
        </protagonistas>
        <generos>
            <genero>Drama</genero>
        </generos>
        <nacionalidades>
            <nacionalidad>USA</nacionalidad>
        </nacionalidades>
    </pelicula>

    <pelicula indice="3">
        <titulo>Spirited Away</titulo>
        <director>Hayao Miyazaki</director>
        <anio>2001</anio>
        <duracion>125 minutes</duracion>
        <protagonistas>
            <actor nombre="Rumi Hiiragi"/>
            <actor nombre="Miyu Irino"/>
        </protagonistas>
        <generos>
            <genero>Animation</genero>
            <genero>Adventure</genero>
            <genero>Fantasy</genero>
        </generos>
        <nacionalidades>
            <nacionalidad>Japan</nacionalidad>
        </nacionalidades>
    </pelicula>

</peliculas>

=== rodrigodelama/PFAT_practicas_22_23/XML/pelis4.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE peliculas SYSTEM "peli.dtd">
<peliculas>
    <pelicula indice="1">
        <titulo>The Dark Knight</titulo>
        <director>Christopher Nolan</director>
        <anio>2008</anio>
        <duracion>152</duracion>
        <protagonistas>
        <actor nombre="Christian Bale" />
        <actor nombre="Heath Ledger" />
        </protagonistas>
        <generos>
        <genero>Action</genero>
        <genero>Drama</genero>
        <genero>Crime</genero>
        </generos>
        <nacionalidades>
        <nacionalidad>USA</nacionalidad>
        <nacionalidad>UK</nacionalidad>
        </nacionalidades>
    </pelicula>
    <pelicula indice="2">
        <titulo>Inception</titulo>
        <director>Christopher Nolan</director>
        <anio>2010</anio>
        <duracion>148</duracion>
        <protagonistas>
        <actor nombre="Leonardo DiCaprio" />
        <actor nombre="Joseph Gordon-Levitt" />
        </protagonistas>
        <generos>
        <genero>Action</genero>
        <genero>Adventure</genero>
        <genero>Sci-Fi</genero>
        </generos>
        <nacionalidades>
        <nacionalidad>USA</nacionalidad>
        <nacionalidad>UK</nacionalidad>
        </nacionalidades>
    </pelicula>
</peliculas>
