=== rodrigodelama/PFAT_practicas_22_23/XML/ord14-15/ord.dtd
<!ELEMENT personal (empleado+)>
<!ELEMENT empleado (nombre,telefono,correo)>
<!ATTLIST empleado id ID #REQUIRED
                   url CDATA #IMPLIED
                   cargo (socio|gerente|consultor) "consultor">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>

=== rodrigodelama/PFAT_practicas_22_23/XML/ord14-15/ord.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personal SYSTEM "ord.dtd">

<personal>
  <empleado id="c1">
    <nombre>Juan Pérez</nombre>
    <telefono>600123456</telefono>
    <correo>juan@pfat.es</correo>
  </empleado>
  <empleado id="c2">
    <nombre>Luis Muñoz</nombre>
    <telefono>609456123</telefono>
    <correo>luis@pfat.es</correo>
  </empleado>
</personal>
